[package]
name = "docker_image"
version = "0.2.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[lib]
name = "docker_image"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[workspace]
members = ["cli"]
