[package]
name = "docker_image_cli"
version = "0.2.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[[bin]]
name = "docker_image_cli"
path = "src/main.rs"
test = true

[dependencies]
clap = "2.25"
docker_image = { path = "../" }
serde_json = "1.0"
